      SUBROUTINE PLANEDISTANCE(X1,Y1,X2,Y2,D12)
      implicit none
      DOUBLE PRECISION :: X1,Y1,X2,Y2,D12, DX,DY
!     D12 IS DISTANCE BETWEEN 1 AND 2 IN PLANE COORDINATES
      DX  = X1 - X2
      DY  = Y1 - Y2
      D12 = SQRT(DX*DX + DY*DY)
      RETURN
      END SUBROUTINE PLANEDISTANCE
