      DOUBLE PRECISION FUNCTION SPLDIST(X,X2,Y,Y2,XX,YY,TV,N)
      implicit none
      integer :: n
!     AFSTAND VAN PUNT XX,YY TOT SPLINEPUNT MET PARM TV

      DOUBLE PRECISION :: X(N), X2(N), Y(N), Y2(N), TV, XX, YY, XV, YV
      TV = MAX(0d0,MIN(TV,N-1d0))
      CALL SPLINT(X,X2,N,TV,XV)
      CALL SPLINT(Y,Y2,N,TV,YV)
!     CALL DISTANCE(XV,YV,XX,YY,DIST)
      CALL PLANEDISTANCE(XV,YV,XX,YY,SPLDIST)
      RETURN
      END FUNCTION SPLDIST
