# bacteria.sub --
#     A basic set-up to model Ecoli bacteria in fresh and saline water.
#     Bacteria are represented by the substance Ecoli.
#
#     Important input:
#     - The irradiation (light intensity), mean over the day
#
#     Inputs of secondary importance:
#     - Salinity (actually modelled as a substance)
#     - Ambient temperature
#     - Day length (depends on the season and the location on Earth)
#
substance 'Salinity' active
   description        'Salinity'
   concentration-unit '(g/kg)'
   waste-load-unit    '-'
end-substance
substance 'EColi' active
   description        'E. Coli bacteria'
   concentration-unit '(MPN/m3)'
   waste-load-unit    '-'
end-substance
parameter 'RcMrtEColi'
   description   'first-order mortality rate EColi'
   unit          '(1/d)'
   value          0.8000E+00
end-parameter
parameter 'Temp'
   description   'ambient water temperature'
   unit          '(oC)'
   value          0.1500E+02
end-parameter
parameter 'DayL'
   description   'daylength <0-1>'
   unit          '(d)'
   value          0.5800E+00
end-parameter
parameter 'ExtVl'
   description   'total extinction coefficient visible light'
   unit          '(1/m)'
   value          0.1000E+01
end-parameter
parameter 'DayRadSurf'
   description   'irradiation at the water surface'
   unit          '(W/m2)'
   value         -0.9990E+03
end-parameter
active-processes
   name  'EColiMrt' 'Mortality EColi bacteria'
   name  'Salinchlor' 'Conversion of salinity into chloride or vv'
   name  'CalcRadDay' 'Actual radiation at segment boundaries'
   name  'DynDepth' 'dynamic calculation of the depth'
end-active-processes
