  SUBROUTINE GAANWESTARTEN(L,K1,KN316,JASTART)
  USE M_NETW
  IMPLICIT NONE
  INTEGER :: L,K1,K2,KN316,JASTART,J, JASTOP, J1, J2

  JASTART = 0
  IF (KN(3,L) /= KN316) RETURN

  DO J = 1,2
     K1 = KN(J,L)
     CALL GAANWESTOPPEN(K1,KN316,JASTART,L)
     IF (JASTART == 1 ) THEN
        RETURN
     ENDIF
  ENDDO

  END SUBROUTINE GAANWESTARTEN
